apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main-app
  template:
    metadata:
      labels:
        app: main-app
    spec:
      containers:
        - name: main
          image: localhost:5000/main:latest
          ports:
            - containerPort: 8000
          env:
            - name: APP_MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: main-config
                  key: APP_MESSAGE
            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: main-secret
                  key: APP_SECRET